// PLAYER
export const CLOSE_PLAYER = 'CLOSE_PLAYER';
export const UPDATE_PLAYER_STATUS = 'UPDATE_PLAYER_STATUS';

// PLAYLIST
export const ADD_SONG_TO_PLAYLIST = 'ADD_SONG_TO_PLAYLIST';
export const FETCH_PLAYLIST = 'FETCH_PLAYLIST';
export const REMOVE_SONG_FROM_PLAYLIST = 'REMOVE_SONG_FROM_PLAYLIST';
export const UPDATE_PLAYLIST_SONG = 'UPDATE_PLAYLIST_SONG';

// FAVORITES
export const ADD_SONG_TO_FAVORITES = 'ADD_SONG_TO_FAVORITES';
export const FETCH_FAVORITES = 'FETCH_FAVORITES';
export const REMOVE_SONG_FROM_FAVORITES = 'REMOVE_SONG_FROM_FAVORITES';
export const UPDATE_FAVORITE = 'UPDATE_FAVORITE';

// SEARCH
export const SEARCH_SONGS_FAILURE = 'SEARCH_SONGS_FAILURE';
export const SEARCH_SONGS_FETCHING = 'SEARCH_SONGS_FETCHING';
export const SEARCH_SONGS_SUCCESS = 'SEARCH_SONGS_SUCCESS';