export const ADD_SONG_TO_FAVORITES = 'ADD_SONG_TO_FAVORITES';
export const ADD_SONG_TO_PLAYLIST = 'ADD_SONG_TO_PLAYLIST';
export const ADD_SONG_TO_PLAYLIST_TOP = 'ADD_SONG_TO_PLAYLIST_TOP';
export const ADD_VOTE_TO_SONG = 'ADD_VOTE_TO_SONG';
export const REMOVE_SONG_FROM_FAVORITES = 'REMOVE_SONG_FROM_FAVORITES';
export const REMOVE_SONG_FROM_PLAYLIST = 'REMOVE_SONG_FROM_PLAYLIST';
export const SEARCH = 'SEARCH';
export const UPDATE_PLAYLIST_SONG_TOP = 'UPDATE_PLAYLIST_SONG_TOP';